//! Cross-stack known-answer test (SPEC-016 REQ-007). The agent SPAKE2
//! initiator must reproduce, byte-for-byte, the same wire values the hub
//! responder produced — pinned by the shared fixture
//! (`tests/fixtures/pairing-vectors.json`, generated by the LFE hub and
//! verified there by its own KAT). If this passes, the Rust client and the
//! LFE hub interoperate by construction, not by hope.

use hark::pairing::{open_record, spake2};
use serde_json::Value;

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn load() -> Value {
    let raw = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/pairing-vectors.json"
    ))
    .expect("fixture present");
    serde_json::from_str(&raw).expect("fixture parses")
}

#[test]
fn agent_initiator_reproduces_hub_vectors() {
    let v = load();
    let inp = &v["inputs"];
    let out = &v["outputs"];

    let hub_id = inp["hub_id"].as_str().unwrap().as_bytes().to_vec();
    let pairing_id = inp["pairing_id"].as_str().unwrap().as_bytes().to_vec();
    let wib = unhex(inp["wib_hex"].as_str().unwrap());
    let x_eph: [u8; 64] = unhex(inp["agent_ephemeral_hex"].as_str().unwrap())
        .try_into()
        .unwrap();

    // The phrase decodes to the same word-index bytes the hub stored.
    let words: Vec<String> = inp["phrase"]
        .as_array()
        .unwrap()
        .iter()
        .map(|w| w.as_str().unwrap().to_string())
        .collect();
    assert_eq!(
        hark::pairing::bip39::phrase_to_wib(&words).unwrap().to_vec(),
        wib,
        "phrase must decode to the stored verifier"
    );

    // Drive the initiator with the fixed ephemeral.
    let mut agent = spake2::Initiator::start(
        spake2::Context::pairing(),
        &wib,
        &pairing_id,
        &hub_id,
        &x_eph,
    );

    // msg_A matches.
    assert_eq!(
        hex(&agent.msg_a()),
        out["msg_a_hex"].as_str().unwrap(),
        "msg_a mismatch — ristretto/transcript interop broken"
    );

    // Feed the hub's msg_B; MAC_A must match.
    let msg_b = unhex(out["msg_b_hex"].as_str().unwrap());
    let mac_a = agent.step1(&msg_b).expect("valid msg_b");
    assert_eq!(hex(&mac_a), out["mac_a_hex"].as_str().unwrap(), "mac_a mismatch");

    // Session key matches.
    assert_eq!(
        hex(&agent.session_key().unwrap()),
        out["session_key_hex"].as_str().unwrap(),
        "session key mismatch"
    );

    // The hub's MAC_B verifies (authenticates the hub).
    let mac_b = unhex(out["mac_b_hex"].as_str().unwrap());
    agent.verify_hub(&mac_b).expect("hub MAC_B must verify");

    // The released ciphertext decrypts under K to the expected record.
    let k = agent.session_key().unwrap();
    let ct = unhex(out["ciphertext_hex"].as_str().unwrap());
    let rec = open_record(&k, &ct).expect("record decrypts under K");
    assert_eq!(rec.agent_name, "@aria");
    assert_eq!(rec.channel, "@research");
    assert!(rec.enc);
    assert!(rec.has_cap(), "private-channel record carries an invite cap");
    assert_eq!(rec.adder, "@mira");
    assert_eq!(rec.dialects.len(), 1);
    assert_eq!(rec.dialects[0].name, "cite");
    assert_eq!(rec.dialects[0].digest, "abc123def456");
    assert_eq!(rec.exp, 9999999999);
}

#[test]
fn wrong_phrase_fails_hub_mac() {
    let v = load();
    let inp = &v["inputs"];
    let out = &v["outputs"];
    let hub_id = inp["hub_id"].as_str().unwrap().as_bytes().to_vec();
    let pairing_id = inp["pairing_id"].as_str().unwrap().as_bytes().to_vec();
    let x_eph: [u8; 64] = unhex(inp["agent_ephemeral_hex"].as_str().unwrap())
        .try_into()
        .unwrap();

    // A wrong phrase → a different wib → a different K → MAC_A won't match the
    // hub's, and the hub's MAC_B won't verify on the agent side either.
    let wrong_wib = hark::pairing::bip39::phrase_to_wib(
        &["abandon", "abandon", "abandon", "abandon"]
            .iter()
            .map(|s| s.to_string())
            .collect::<Vec<_>>(),
    )
    .unwrap();
    let mut agent = spake2::Initiator::start(
        spake2::Context::pairing(),
        &wrong_wib,
        &pairing_id,
        &hub_id,
        &x_eph,
    );
    let msg_b = unhex(out["msg_b_hex"].as_str().unwrap());
    let _ = agent.step1(&msg_b).expect("msg_b is still a valid point");
    let mac_b = unhex(out["mac_b_hex"].as_str().unwrap());
    assert!(
        agent.verify_hub(&mac_b).is_err(),
        "a wrong phrase must not authenticate the hub"
    );
}

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}
