//! Group-state-bound pairing v3 — the shared known-answer vector
//! (`tests/vectors/pairgrant-v3-context-vector.json`, sha256 in the sibling
//! `.sha256`). The JSON was generated by an independent Python implementation
//! (`gen_pairgrant_v3_vector.py`) written from the decision text, not from this
//! crate, and is the vector the browser contract (cbcl-bus `cbcl-mls-wasm`) MUST
//! check byte-for-byte too. A pairing grant is always minted on one stack and
//! redeemed on the other, so a drift here is every pairing admission refused.

use base64::{Engine as _, engine::general_purpose::STANDARD as B64};
use hark::chat_frame::FrameSigner as _;
use hark::identity::ChatIdentity;
use hark::mls::DS_MLS_PAIRGRANT;
use hark::mls::group::{GenesisAssertion, PairingGrant, verify_admission_authority};
use hark::mls::pins::pairgrant_signing_bytes;
use openmls::prelude::GroupContext;
use serde_json::Value;
use sha2::{Digest as _, Sha256};
use tls_codec::{DeserializeBytes as _, Serialize as _};

const VECTOR: &str = include_str!("vectors/pairgrant-v3-context-vector.json");
const VECTOR_SHA256: &str = include_str!("vectors/pairgrant-v3-context-vector.sha256");

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn arr32(v: &[u8]) -> [u8; 32] {
    <[u8; 32]>::try_from(v).unwrap()
}

fn load() -> Value {
    serde_json::from_str(VECTOR).unwrap()
}

/// The file the browser consumes is exactly the file checked here.
#[test]
fn vector_file_matches_its_recorded_digest() {
    let digest = hex(&Sha256::digest(VECTOR.as_bytes()));
    let recorded = VECTOR_SHA256.split_whitespace().next().unwrap();
    assert_eq!(
        digest, recorded,
        "pairgrant-v3-context-vector.json changed without its .sha256"
    );
}

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

/// Every GroupContext in the vector is a real, canonical RFC 9420 GroupContext:
/// OpenMLS (the codec hark reads contexts with) parses it and re-serializes it
/// to the same bytes, for the group id the case names.
#[test]
fn vector_group_contexts_are_canonical_openmls_contexts() {
    let v = load();
    let mut all = vec![
        v["inputs"]["group_context_hex"]
            .as_str()
            .unwrap()
            .to_string(),
    ];
    for case in v["cases"].as_array().unwrap() {
        all.push(case["group_context_hex"].as_str().unwrap().to_string());
    }
    for hex_ctx in all {
        let bytes = unhex(&hex_ctx);
        let (ctx, rest) = GroupContext::tls_deserialize_bytes(&bytes).unwrap();
        assert!(rest.is_empty(), "no trailing bytes after {hex_ctx}");
        assert_eq!(
            ctx.tls_serialize_detached().unwrap(),
            bytes,
            "canonical: {hex_ctx}"
        );
    }
    let (ctx, _) = GroupContext::tls_deserialize_bytes(&unhex(
        v["inputs"]["group_context_hex"].as_str().unwrap(),
    ))
    .unwrap();
    assert_eq!(hex(ctx.group_id().as_slice()), v["inputs"]["group_id_hex"]);
    assert_eq!(ctx.epoch().as_u64(), 7);
}

#[test]
fn hark_reproduces_the_v3_context_signature_and_grant() {
    let v = load();
    let i = &v["inputs"];
    assert_eq!(i["label"], DS_MLS_PAIRGRANT, "hark's label is the vector's");
    let group_id = unhex(i["group_id_hex"].as_str().unwrap());
    let group_context = unhex(i["group_context_hex"].as_str().unwrap());
    let signer = ChatIdentity::from_seed(arr32(&unhex(i["signer_seed_hex"].as_str().unwrap())));
    let subject = ChatIdentity::from_seed(arr32(&unhex(i["subject_seed_hex"].as_str().unwrap())));
    assert_eq!(hex(&signer.verifying_key_bytes()), i["signer_key_hex"]);
    assert_eq!(hex(&subject.verifying_key_bytes()), i["subject_key_hex"]);
    let room = i["room"].as_str().unwrap();
    let not_after = i["not_after_ms"].as_u64().unwrap();

    let ctx = pairgrant_signing_bytes(
        room,
        &group_id,
        &group_context,
        i["signer_handle"].as_str().unwrap(),
        &signer.verifying_key_bytes(),
        i["subject_handle"].as_str().unwrap(),
        &subject.verifying_key_bytes(),
        not_after,
    );
    assert_eq!(
        hex(&ctx),
        v["context_hex"],
        "v3 signed context drifted from the shared vector"
    );
    assert_eq!(hex(&Sha256::digest(&ctx)), v["context_sha256_hex"]);

    let sig = signer.sign(&ctx);
    assert_eq!(
        B64.encode(sig),
        v["signature_b64"],
        "Ed25519 over the context is deterministic"
    );

    // hark's serialization of that grant is the vector's JSON (key order is not
    // normative across stacks; it is pinned here so hark's own output is stable).
    let grant = PairingGrant {
        kind: DS_MLS_PAIRGRANT.to_string(),
        room: room.to_string(),
        group_id_b64: B64.encode(&group_id),
        group_context_b64: B64.encode(&group_context),
        signer_handle: i["signer_handle"].as_str().unwrap().to_string(),
        signer_key_b64: B64.encode(signer.verifying_key_bytes()),
        subject_handle: i["subject_handle"].as_str().unwrap().to_string(),
        subject_key_b64: B64.encode(subject.verifying_key_bytes()),
        not_after_ms: not_after,
        sig_b64: B64.encode(sig),
    };
    assert_eq!(serde_json::to_string(&grant).unwrap(), v["grant_json"]);
}

/// Every case through the same dispatch + verify the member and the joiner run.
#[test]
fn hark_decides_every_vector_case_as_recorded() {
    let v = load();
    let i = &v["inputs"];
    let room = i["room"].as_str().unwrap();
    let subject_handle = i["subject_handle"].as_str().unwrap();
    let subject_key = unhex(i["subject_key_hex"].as_str().unwrap());
    let leaves: Vec<(String, Vec<u8>)> = v["verify_live_leaves"]
        .as_array()
        .unwrap()
        .iter()
        .map(|l| {
            (
                l["handle"].as_str().unwrap().to_string(),
                unhex(l["key_hex"].as_str().unwrap()),
            )
        })
        .collect();
    // Never consulted on the pairing path; present because an invite would be.
    let genesis = GenesisAssertion {
        room: room.to_string(),
        creator_handle: "@nobody".into(),
        group_id_b64: String::new(),
        creator_key_b64: B64.encode([0u8; 32]),
        signature_b64: String::new(),
    };
    let cases = v["cases"].as_array().unwrap();
    assert!(cases.len() >= 11);
    for case in cases {
        let name = case["name"].as_str().unwrap();
        let now = case["now_ms"]
            .as_u64()
            .unwrap_or(v["verify_now_ms"].as_u64().unwrap());
        let result = verify_admission_authority(
            case["grant_json"].as_str().unwrap(),
            "",
            room,
            &unhex(case["group_id_hex"].as_str().unwrap()),
            &unhex(case["group_context_hex"].as_str().unwrap()),
            subject_handle,
            &subject_key,
            &leaves,
            &genesis,
            now,
        );
        let expect = case["expect"].as_str().unwrap();
        match (expect, &result) {
            ("accept", Ok(())) => {}
            ("reject:group", Err(e)) => {
                assert!(
                    e.to_string().contains("different MLS group than"),
                    "{name}: {e}"
                )
            }
            ("reject:context", Err(e)) => assert!(
                e.to_string().contains("stale or different MLS group state"),
                "{name}: {e}"
            ),
            ("reject:signature", Err(e)) => {
                assert!(e.to_string().contains("does not verify"), "{name}: {e}")
            }
            ("reject:kind", Err(e)) => {
                assert!(e.to_string().contains("not supported"), "{name}: {e}")
            }
            ("reject:record", Err(e)) => {
                assert!(e.to_string().contains("pairing grant json"), "{name}: {e}")
            }
            ("reject:expired", Err(e)) => assert!(e.to_string().contains("expired"), "{name}: {e}"),
            _ => panic!("vector case {name}: expected {expect}, got {result:?}"),
        }
    }
}
